name: Build and Test
on:
  push:
    branches: [ galactic ]
  pull_request:
    branches: [ galactic ]
  schedule:
    - cron: '0 21 * * *'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Check Changed files
        id: check_changed_files
        uses: tj-actions/changed-files@v9.2
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic
      - name: Build rmoss_core
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: "${{ github.workspace }}/tools/dependency.repos"
          skip-tests: true
      - name: Test rmoss_util
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select rmoss_util --event-handlers console_cohesion+ --return-code-on-test-failure
      - name: Test rmoss_base
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select rmoss_base --event-handlers console_cohesion+ --return-code-on-test-failure
      - name: Test rmoss_cam
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select rmoss_cam --event-handlers console_cohesion+ --return-code-on-test-failure
      - name: Test rmoss_projectile_motion
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select rmoss_projectile_motion --event-handlers console_cohesion+ --return-code-on-test-failure