name: Build and Test
on:
  push:
    branches: [ galactic ]
  pull_request:
    branches: [ galactic ]
  schedule:
    - cron: '0 21 * * *'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-desktop-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build rmoss_core
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: "${{ github.workspace }}/tools/dependency.repos"
          skip-tests: true
      - name: Test rmoss_util
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh rmoss_util
      - name: Test rmoss_base
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh rmoss_base
      - name: Test rmoss_cam
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh rmoss_cam
      - name: Test rmoss_projectile_motion
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh rmoss_projectile_motion
